# Generated by Django 3.2.11 on 2022-01-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='noti_type',
            field=models.CharField(choices=[('1', 'Follow'), ('2', 'Comment'), ('3', 'Like')], default=None, max_length=25),
            preserve_default=False,
        ),
    ]
