# Generated by Django 4.0 on 2021-12-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_is_seller_user_bio_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
