# Generated by Django 3.2.11 on 2022-05-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_post'),
    ]

    def generate_superuser(apps, schema_editor):
        from core.models import User
        
        superuser = User.objects.create_superuser(
            email="admin@admin.com",
            password="admin")
        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
