# Generated by Django 4.0 on 2021-12-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_bio_user_profile_photo_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default-user-icon-13.jpg', null=True, upload_to=''),
        ),
    ]
