# Generated by Django 3.2.11 on 2022-01-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
    ]
