# Generated by Django 4.0 on 2021-12-29 04:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='comment',
        ),
        migrations.AddField(
            model_name='likes',
            name='comment',
            field=models.ManyToManyField(to='socialuser.Comments'),
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ManyToManyField(to='socialuser.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 4, 5, 46, 106971, tzinfo=utc)),
        ),
    ]
