# Generated by Django 4.0 on 2022-01-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
        migrations.AddField(
            model_name='story',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_profile', to='socialuser.profile'),
        ),
    ]
