# Generated by Django 4.0 on 2021-12-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0002_remove_likes_like_remove_likes_comment_likes_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialuser.comments'),
        ),
    ]
