# Generated by Django 4.0 on 2021-12-29 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0002_remove_likes_comment_likes_comment_remove_likes_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 5, 35, 50, 349692, tzinfo=utc)),
        ),
    ]
