# Generated by Django 4.0 on 2022-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0002_postgres_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='story',
        ),
        migrations.RemoveField(
            model_name='video',
            name='story',
        ),
        migrations.AddField(
            model_name='story',
            name='content',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
