# Generated by Django 3.2.11 on 2022-01-24 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0004_auto_20220124_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcomments', to='socialuser.post'),
        ),
    ]
