# Generated by Django 4.0 on 2022-01-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_user'),
        ('socialuser', '0004_remove_story_user_story_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='profile',
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
