# Generated by Django 3.2.11 on 2022-01-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0005_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
