# Generated by Django 4.0 on 2022-01-07 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialuser', '0006_comment_liked_by_post_liked_by_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
