# Generated by Django 3.2.11 on 2022-01-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
    ]
