# Generated by Django 4.0 on 2022-01-07 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialuser', '0007_alter_comment_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
