# Generated by Django 3.2.11 on 2022-01-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0007_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstory', to='socialuser.profile'),
        ),
    ]
