# Generated by Django 3.2.11 on 2022-01-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0009_alter_story_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='profile',
            new_name='user',
        ),
    ]
