# Generated by Django 3.2.11 on 2022-01-24 07:59

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0009_alter_comment_post'),
    ]

    operations = [
        TrigramExtension(),
    ]