# Generated by Django 4.0 on 2022-01-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0010_alter_comment_liked_by_alter_post_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True)),
                ('product', models.ManyToManyField(related_name='tag_product', to='socialuser.Post')),
            ],
        ),
    ]
