# Generated by Django 3.2.11 on 2022-01-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0011_auto_20220120_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_story',
        ),
    ]
