# Generated by Django 3.2.11 on 2022-01-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0010_alter_comment_post'),
        ('socialuser', '0011_postgres_search'),
    ]

    operations = [
    ]
