# Generated by Django 3.2.11 on 2022-01-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0003_alter_profile_user'),
        ('socialuser', '0012_remove_profile_active_story'),
    ]

    operations = [
    ]
