# Generated by Django 4.0 on 2022-01-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0013_media_remove_video_post_delete_image_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
