# Generated by Django 3.2.11 on 2022-01-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0018_alter_profile_user_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='tag_post', to='socialuser.Post'),
        ),
    ]
