# Generated by Django 3.2.11 on 2022-01-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0020_auto_20220117_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='socialuser.Tag'),
        ),
    ]
